### ISSUE TITLE
prendre une piece

### ISSUE THREAD

**Issue by ntaffore** [Lucas-C/tablut#11]

**Comment by Lucas-C** [comment]
Commit: https://github.com/Lucas-C/tablut/commit/cdd0a7b6e3cf7749ee0726c45afa1bc7e1350032

**Comment by ntaffore** [comment]
Vérifier en fonction des règles que le rois peux être capturer si il n'est encerclé que de 3 pièces adverse et d'un de ses alliés ? 
fonctionne dans certain cas mais pas dans d'autre:
Si la pièce allié est à droite du rois le rois est pris mais s'il est est en dessous il ne semble pas pris (à vérifier)

**Comment by Lucas-C** [comment]
Bien vu !

**Comment by Lucas-C** [comment]
Après vérification, c'est le comportement attendu:
si les pièces encerclant le roi incluent un pion allié, il n'est pas capturé

**Comment by Lucas-C** [comment]
Au final, il y avait un bug, corrigé en #0f5c24b
