### ISSUE TITLE
règles de mouvements autorisés (partie php)

### ISSUE THREAD

**Issue by Lucas-C** [Lucas-C/tablut#12]

**Comment by ntaffore** [comment]
Commit 2d98252

**Comment by Lucas-C** [comment]
Beau boulot !

Attention, le build Travis est cassé ! :)
https://travis-ci.org/Lucas-C/tablut
Juste un petit problème d'espace je crois. C'est possible de fixer ça automatiquement en exécutant `composer fix-php`

**Comment by Lucas-C** [comment]
Je t'ai fait quelques petits retours, mais c'est génial que t'ai réussi à l'implémenter !
Dans l'ensemble, ce serait juste top de réduire un peu la taille de ce code

**Comment by ntaffore** [comment]
J'aime bien les codes qui prennent de la place. Je pense donc le laisser pour l'instant.
Il faut bien qu'on fasse un peu d'obsolescence programmé !
