### ISSUE TITLE
Affichage spécifique raichi/tuichi

### ISSUE THREAD

**Issue by ntaffore** [Lucas-C/tablut#14]
>  Quand le roi a directement une voie libre jusqu'à la périphérie, il doit avertir son adversaire en disant **raichi**. Quand il a deux voies libres, il annonce triomphalement **tuichi**; dans ce cas, il a gagné le coup suivant parce qu'on ne peut pas bloquer simultanément deux voies libres.

**Comment by Lucas-C** [comment]
TODO: Tooltip + colorer les cases de déplacement
