### ISSUE TITLE
Pre-release check-list

### ISSUE THREAD

**Issue by Lucas-C** [Lucas-C/tablut#24]
From: http://studio.boardgamearena.com/#!doc/Pre-release_checklist

### Metadata and graphics
- [x] Game_meta-information: `gameinfos.inc.php` has correct and up to date information about the game
- [x] Game box graphics is 3D version of the game box (if available) and publisher icon is correct (see Game art: img directory). Space around the box has to be transparent, not white.
- [x] There is no images in img directory which are not needed anymore
- [x] Multiple images (i.e. cards) are compressed in "Sprite" (see Game art: img directory)
- [x] Each image should not exceed 4M
- [x] Total size should not exceed 10M, image compression should be used otherwise 

### Server side
- [x] Game progression is implemented (getGameProgression() in php)
- [x] Zombie turn is implemented (zombieTurn() in php). Note: it can only be tested with two different studio accounts (dev0 and devzombi0 for example, not dev0 and dev1)
- [x] You have defined and implemented some meaningful statistics for your game (i.e. total points, point from source A, B, C...)
- [x] Game has meaningful notification messages (but don't overkill it, more user logs will slow down the loading)
- [NA] You implemented tiebreaking (using aux score field) and updated tiebreaker description in meta-data - cf. http://en.doc.boardgamearena.com/Main_game_logic:_yourgamename.game.php#Manage_player_scores_and_Tie_breaker

### Special testing
- [x] Game is tested with spectator (non player observer)
- [ ] Game is tested with in-game replay feature (by clicking on notification log items)
- [x] Game works in Chrome and Firefox browsers at least. Also very recommended to test in IE 11 and Edge.
- [x] Game works on mobile device (if you don't have mobile device to test at least test in Chrome with smaller screen, they have a mode for that)
- [x] Test your game in realtime mode. Usually people will run out of time if you use default times unless you add call giveExtraTime($active_player_id) before each turn
- [x] Test your game in 3D mode 

### Cleanup
- [x] Remove all extra console.log from your js code
- [x] Remove all unnecessary debug logging from your php code
- [x] Copyright headers in all source files have your name 

### User Interface
- [x] Review BGA UI design Guidelines BGA_Studio_Guidelines : https://en.boardgamearena.com/#!doc/BGA_Studio_Guidelines
    * [x] tester rendu sur petit écran ? (la doc des guidelines indique qu'il faut supporter au minimum du 1024px de large)
    * [x] ajouter plus d'infos dans le "gamelog" ?
- [x] Non-self explanatory graphic elements should have tooltips
- [x] If graphic elements appear in notification log they should have titles (i.e. title attribute of div) so can be read in non rendered form (i.e. as text only)
- [x] Strings in your source code are ready for translation. See Translations 

### Finally
- [ ] Send e-mail to bga admins asking for review of the game, you cannot post to pre-production yourself using control panel until review is done and they unlock it. If they don't reply post on dev forum.

**Comment by Lucas-C** [comment]
\+ tester rendu sur petit écran ?

**Comment by ntaffore** [comment]
replay game
"Sorry, an unexpected error has occurred...

Game archive not found

#0 /var/tournoi/release/tournoi-180503-0914/www/action/gamereview/gamereview.action.php(36): Archive->unarchivetablelogs('46891')
#1 /var/tournoi/release/tournoi-180503-0914/www/include/webActionCore.inc.php(133): action_gamereview->__default()
#2 /var/tournoi/release/tournoi-180503-0914/www/index.php(152): launchWebAction('gamereview', 'action_gamerevi...', '__default', false, false, NULL, true, false)
#3 {main}
"

**Comment by Lucas-C** [comment]
Done
