### ISSUE TITLE
Feedbacks admins BGA

### ISSUE THREAD

**Issue by Lucas-C** [Lucas-C/tablut#28]
- [x] La mention "You play the black pawns, the muscovites" élargit la zone de statut et ne disparaît pas après le début de partie sauf en cas de refresh. Vous pouvez simplement l'afficher dans le log avec notifyPlayer au début de la partie. De manière générale, afficher un bloc supplémentaire au dessus de la barre de statut ne correspond pas au fonctionnement général sur BGA. Il vaut mieux afficher l'information dans le log, et le cas échéant un "showMessage( _('message'), 'info' )" côté javascript si on veut attirer particulièrement l'attention.

- [x] L'icône que vous avez choisi pour le jeu utilise un fond "bois", alors que le style que vous avez choisi à l'intérieur du jeu est sur fond blanc. Il faudrait que les deux soient cohérents.

- [x] Toutes les cases du plateau sont mises en surbrillance quand on les survole avec le curseur de la souris. Il vaudrait mieux que ce soient les pions du joueur courant qui soient mis en surbrillance.

- [x] Comme pour les échecs et la plupart des jeux abstraits, c'est bien d'indiquer des coordonnées de colonnes A B C D... et de lignes 1 2 3 4... à côté du plateau et de mentionner précisément les coups dans le log, par exemple "Een moves a piece from H5 to H3", "Een captured a piece in E8"

*Note @lucas-c:* il faudra alors rajouter à gauche du plateau les noms de lignes (A, B, C...) et en bas ceux des colonnes (1, 2, 3...)

- [x] Les pions capturés disparaissent directement, ce qui est un peu rapide et pas très visuel. Il vaudrait mieux soit les déplacer en dehors du plateau dans une "zone de capture", soit les déplacer vers le nom du joueur en haut à droite et les faire disparaître ensuite.

- [x] Pour l'option de début de partie, il vaudrait mieux l'appeler "Variant" avec deux valeurs "King escapes from the borders" et "King espapes from the corners", ce serait plus clair.

- [x] Dans les règles que j'ai trouvées, le roi ne participe pas à la capture http://www.stmoroky.com/games/tablut/tabrules.htm

*Note @lucas-c:* la moitié de celles que j'ai trouvé semblent l’autoriser :
- https://www.jeux-terre-bois.com/images/PDF/tablut.pdf
- http://www.lecomptoirdesjeux.com/tablut-hnefatafl-et-autres-jeux-nordiques.htm
- http://www.ludoteka.com/tablut-fr.html
- http://jeuxstrategieter.free.fr/Tablut_complet.php
- http://tafl.cyningstan.com/page/170/tablut

- [x] Quand le roi est capturé, il ne devrait pas disparaître, pour que la situation de fin de jeu soit complètement visible, et le message dans le log devrait être différent, du type "Een captured the King in E8"

- [x] Dans la barre de statut, les pions sont appelés "disc" et dans le log "pawn" -> il faut utiliser la même terminologie partout

- [x] En cas de 'Raichi', l'indiquer dans le log avec une explication "Raichi! (the King gained an open path to a corner)" + éventuellement un "showMessage( _('message'), 'info' )"

*Note @lucas-c:* comme les notifs ne peuvent être envoyées que côté PHP, ça signifie implémenter la détection de RAICHI / TUICHI de ce côté là aussi...

- [x] Quand il y a 'Tuichi', c'est la fin du jeu. On peut directement indiquer "Tuichi! (the King gained two clear paths to corners: the game ends)" dans le log + éventuellement un "showMessage( _('message'), 'info' )" et faire gagner les blancs puisque les noirs n'ont plus aucun moyen de bloquer le roi.

- [x] Quand on survole les coins et le konakis avec la variante "King escapes from the corners", un tooltip s'affiche avec le texte "No one can enter fortress squares". Le texte devrait être "Only the king may occupy the konakis and the corner squares".

- [x] Le roi doit pouvoir revenir au centre / passer par le centre. Les autres pièces doivent pouvoir traverser le centre sans s'y arrêter (à mon avis, pour les deux variantes, mais en tout cas au moins pour la variante 'corners').

*Note @lucas-c:* nous nous étions basés sur cette règle qui interdit le passage par la case centrale ; http://jeuxstrategieter.free.fr/Tablut_complet.php , mais après un rapide tour des autres règles que j'ai trouvé sur le web en français et anglais, ça paraît en effet la règle la plus courante : cette case peut être traversée par tous les pions, mais ne peut être occupée que par le roi et peut servir à le capturer.

**Comment by Lucas-C** [comment]
Je suis vraiment pas convaincu par le rendu du `showMessage` :(
![showmessage](https://user-images.githubusercontent.com/925560/41822503-dbf2ed96-77f0-11e8-9178-90468aa2458e.png)

**Comment by Lucas-C** [comment]
- [x] passer la souris au dessus des pions noirs les fait ressembler à des pions blancs -> améliorer ça

**Comment by ntaffore** [comment]
- [x] il faut changer le texte de konakis pour la variante
